{
  "hash": "aed1be276193cdd75a8b39cb87f125e0",
  "result": {
    "engine": "jupyter",
    "markdown": "# HW 1\n\n---\ntitle: \"A Replication of Karlan and List (2007)\"\nauthor: \"Alexa Gamble\"\ndate: 04/17/2025\ncallout-appearance: minimal # this hides the blue \"i\" icon on .callout-notes\n---\n\n\n## Introduction\n\nDean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the _American Economic Review_ in 2007. The article and supporting data are available from the [AEA website](https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774) and from Innovations for Poverty Action as part of [Harvard's Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&version=4.2).\n\n_to do: expand on the description of the experiment._\n\nThis project seeks to replicate their results.\n\n\n## Data\n\n### Description\n\n::: {#074df68e .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\ndf_k = pd.read_stata(\"/home/jovyan/Desktop/MGTA 495 - Marketing Analytics/karlan_list_2007.dta\")\ndf_k\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>treatment</th>\n      <th>control</th>\n      <th>ratio</th>\n      <th>ratio2</th>\n      <th>ratio3</th>\n      <th>size</th>\n      <th>size25</th>\n      <th>size50</th>\n      <th>size100</th>\n      <th>sizeno</th>\n      <th>...</th>\n      <th>redcty</th>\n      <th>bluecty</th>\n      <th>pwhite</th>\n      <th>pblack</th>\n      <th>page18_39</th>\n      <th>ave_hh_sz</th>\n      <th>median_hhincome</th>\n      <th>powner</th>\n      <th>psch_atlstba</th>\n      <th>pop_propurban</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>1</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>...</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.446493</td>\n      <td>0.527769</td>\n      <td>0.317591</td>\n      <td>2.10</td>\n      <td>28517.0</td>\n      <td>0.499807</td>\n      <td>0.324528</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>0</td>\n      <td>1</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>...</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>$100,000</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>...</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.935706</td>\n      <td>0.011948</td>\n      <td>0.276128</td>\n      <td>2.48</td>\n      <td>51175.0</td>\n      <td>0.721941</td>\n      <td>0.192668</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>Unstated</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>...</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.888331</td>\n      <td>0.010760</td>\n      <td>0.279412</td>\n      <td>2.65</td>\n      <td>79269.0</td>\n      <td>0.920431</td>\n      <td>0.412142</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>$50,000</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>...</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.759014</td>\n      <td>0.127421</td>\n      <td>0.442389</td>\n      <td>1.85</td>\n      <td>40908.0</td>\n      <td>0.416072</td>\n      <td>0.439965</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>50078</th>\n      <td>1</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>$25,000</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>...</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.872797</td>\n      <td>0.089959</td>\n      <td>0.257265</td>\n      <td>2.13</td>\n      <td>45047.0</td>\n      <td>0.771316</td>\n      <td>0.263744</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>50079</th>\n      <td>0</td>\n      <td>1</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>...</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.688262</td>\n      <td>0.108889</td>\n      <td>0.288792</td>\n      <td>2.67</td>\n      <td>74655.0</td>\n      <td>0.741931</td>\n      <td>0.586466</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>50080</th>\n      <td>0</td>\n      <td>1</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>Control</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>...</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.900000</td>\n      <td>0.021311</td>\n      <td>0.178689</td>\n      <td>2.36</td>\n      <td>26667.0</td>\n      <td>0.778689</td>\n      <td>0.107930</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>50081</th>\n      <td>1</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0</td>\n      <td>1</td>\n      <td>Unstated</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>...</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.917206</td>\n      <td>0.008257</td>\n      <td>0.225619</td>\n      <td>2.57</td>\n      <td>39530.0</td>\n      <td>0.733988</td>\n      <td>0.184768</td>\n      <td>0.634903</td>\n    </tr>\n    <tr>\n      <th>50082</th>\n      <td>1</td>\n      <td>0</td>\n      <td>3</td>\n      <td>0</td>\n      <td>1</td>\n      <td>$25,000</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>...</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.530023</td>\n      <td>0.074112</td>\n      <td>0.340698</td>\n      <td>3.70</td>\n      <td>48744.0</td>\n      <td>0.717843</td>\n      <td>0.127941</td>\n      <td>0.994181</td>\n    </tr>\n  </tbody>\n</table>\n<p>50083 rows × 51 columns</p>\n</div>\n```\n:::\n:::\n\n\nThe dataset consists of **50,083 observations** and **51 variables**, and appears to originate from a field experiment or observational study, likely related to donation behavior or outreach strategies. Each row represents an individual unit (e.g., a household or donor), and the dataset includes both treatment assignments and a range of covariates.\n\n#### Key Variables\n\n- **`treatment`**, **`control`**: Binary indicators denoting experimental group assignment. A value of `1` in `treatment` indicates the subject received the treatment condition, while `1` in `control` indicates assignment to the control group. These two variables are mutually exclusive.\n- **`ratio`**, **`ratio2`**, **`ratio3`**: Variables reflecting matching incentives (e.g., 1:1, 2:1 matches) provided during the intervention. These are likely categorical or indicator variables showing the ratio level applied.\n- **`size`**, **`size25`**, **`size50`**, **`size100`**, **`sizeno`**: Donation ask size variables. The `size` column includes textual representations of the suggested donation amount (e.g., `\"$100,000\"`), while the other columns serve as binary indicators for specific size categories.\n\n#### Demographic & Contextual Variables\n\n- **`redcty`**, **`bluecty`**: Indicators of political affiliation or voting patterns in the subject’s county or city.\n- **`pwhite`**, **`pblack`**: Proportion of white and Black residents in the geographic area.\n- **`page18_39`**: Proportion of the population between ages 18 and 39.\n- **`ave_hh_sz`**: Average household size.\n- **`median_hhincome`**: Median household income in the area.\n- **`powner`**: Proportion of homeowners.\n- **`psch_atlstba`**: Proportion of the population with at least a bachelor's degree.\n- **`pop_propurban`**: Proportion of the population living in urban areas.\n\n#### Missing Data\n\nSeveral rows contain missing values (`NaN`), especially in demographic variables like `pwhite`, `pblack`, and `median_hhincome`. These may result from incomplete geographic data or limitations in census coverage.\n\n\n\n:::: {.callout-note collapse=\"true\"}\n### Variable Definitions\n\n| Variable             | Description                                                         |\n|----------------------|---------------------------------------------------------------------|\n| `treatment`          | Treatment                                                           |\n| `control`            | Control                                                             |\n| `ratio`              | Match ratio                                                         |\n| `ratio2`             | 2:1 match ratio                                                     |\n| `ratio3`             | 3:1 match ratio                                                     |\n| `size`               | Match threshold                                                     |\n| `size25`             | \\$25,000 match threshold                                            |\n| `size50`             | \\$50,000 match threshold                                            |\n| `size100`            | \\$100,000 match threshold                                           |\n| `sizeno`             | Unstated match threshold                                            |\n| `ask`                | Suggested donation amount                                           |\n| `askd1`              | Suggested donation was highest previous contribution                |\n| `askd2`              | Suggested donation was 1.25 x highest previous contribution         |\n| `askd3`              | Suggested donation was 1.50 x highest previous contribution         |\n| `ask1`               | Highest previous contribution (for suggestion)                      |\n| `ask2`               | 1.25 x highest previous contribution (for suggestion)               |\n| `ask3`               | 1.50 x highest previous contribution (for suggestion)               |\n| `amount`             | Dollars given                                                       |\n| `gave`               | Gave anything                                                       |\n| `amountchange`       | Change in amount given                                              |\n| `hpa`                | Highest previous contribution                                       |\n| `ltmedmra`           | Small prior donor: last gift was less than median \\$35              |\n| `freq`               | Number of prior donations                                           |\n| `years`              | Number of years since initial donation                              |\n| `year5`              | At least 5 years since initial donation                             |\n| `mrm2`               | Number of months since last donation                                |\n| `dormant`            | Already donated in 2005                                             |\n| `female`             | Female                                                              |\n| `couple`             | Couple                                                              |\n| `state50one`         | State tag: 1 for one observation of each of 50 states; 0 otherwise  |\n| `nonlit`             | Nonlitigation                                                       |\n| `cases`              | Court cases from state in 2004-5 in which organization was involved |\n| `statecnt`           | Percent of sample from state                                        |\n| `stateresponse`      | Proportion of sample from the state who gave                        |\n| `stateresponset`     | Proportion of treated sample from the state who gave                |\n| `stateresponsec`     | Proportion of control sample from the state who gave                |\n| `stateresponsetminc` | stateresponset - stateresponsec                                     |\n| `perbush`            | State vote share for Bush                                           |\n| `close25`            | State vote share for Bush between 47.5% and 52.5%                   |\n| `red0`               | Red state                                                           |\n| `blue0`              | Blue state                                                          |\n| `redcty`             | Red county                                                          |\n| `bluecty`            | Blue county                                                         |\n| `pwhite`             | Proportion white within zip code                                    |\n| `pblack`             | Proportion black within zip code                                    |\n| `page18_39`          | Proportion age 18-39 within zip code                                |\n| `ave_hh_sz`          | Average household size within zip code                              |\n| `median_hhincome`    | Median household income within zip code                             |\n| `powner`             | Proportion house owner within zip code                              |\n| `psch_atlstba`       | Proportion who finished college within zip code                     |\n| `pop_propurban`      | Proportion of population urban within zip code                      |\n\n::::\n\n\n### Balance Test \n\nAs an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.\n\n_todo: test a few variables other than the key outcome variables (for example, test months since last donation) to see if the treatment and control groups are statistically significantly different at the 95% confidence level. Do each as a t-test and separately as a linear regression, and confirm you get the exact same results from both methods. When doing a t-test, use the formula in the class slides. When doing the linear regression, regress for example mrm2 on treatment and look at the estimated coefficient on the treatment variable. It might be helpful to compare parts of your analysis to Table 1 in the paper. Be sure to comment on your results (hint: why is Table 1 included in the paper)._\n\nTo assess whether the random assignment mechanism was successful, I conduct balance tests on three baseline variables that are not influenced by treatment:\n\n- `mrm2`: months since last donation  \n- `pwhite`: proportion of white residents in the donor’s area  \n- `ave_hh_sz`: average household size\n\nFor each variable, I apply both a **manual t-test** and a **linear regression** to compare treatment and control groups. These methods should yield consistent results, since both estimate the same underlying difference in means.\n\n::: {#165324d1 .cell execution_count=2}\n``` {.python .cell-code}\nimport numpy as np\nimport statsmodels.formula.api as smf\n\n# Function to compute manual t-test and regression for a given variable\ndef balance_test(df, variable, treatment_col=\"treatment\"):\n    df_clean = df.dropna(subset=[variable, treatment_col])\n    treat = df_clean[df_clean[treatment_col] == 1][variable]\n    control = df_clean[df_clean[treatment_col] == 0][variable]\n\n    # Manual t-test\n    mean_treat = treat.mean()\n    mean_control = control.mean()\n    var_treat = treat.var(ddof=1)\n    var_control = control.var(ddof=1)\n    n_treat = len(treat)\n    n_control = len(control)\n    se = np.sqrt(var_treat/n_treat + var_control/n_control)\n    t_stat = (mean_treat - mean_control) / se\n\n    # Welch's degrees of freedom\n    df_num = (var_treat/n_treat + var_control/n_control)**2\n    df_denom = ((var_treat/n_treat)**2 / (n_treat - 1)) + ((var_control/n_control)**2 / (n_control - 1))\n    df_eff = df_num / df_denom\n\n    print(f\"\\n=== Balance Test: {variable} ===\")\n    print(f\"Manual t-test: t = {t_stat:.4f}, df ≈ {df_eff:.2f}\")\n\n    # Linear regression\n    formula = f\"{variable} ~ {treatment_col}\"\n    model = smf.ols(formula, data=df_clean).fit()\n    coef = model.params[treatment_col]\n    pval = model.pvalues[treatment_col]\n    print(f\"Regression coefficient on treatment: {coef:.4f}, p = {pval:.4f}\")\n    return model.summary()\n\nbalance_test(df_k, \"mrm2\")\nbalance_test(df_k, \"pwhite\")\nbalance_test(df_k, \"ave_hh_sz\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=== Balance Test: mrm2 ===\nManual t-test: t = 0.1195, df ≈ 33394.48\nRegression coefficient on treatment: 0.0137, p = 0.9049\n\n=== Balance Test: pwhite ===\nManual t-test: t = -0.5590, df ≈ 31876.22\nRegression coefficient on treatment: -0.0009, p = 0.5753\n\n=== Balance Test: ave_hh_sz ===\nManual t-test: t = 0.8234, df ≈ 31960.02\nRegression coefficient on treatment: 0.0030, p = 0.4098\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<table class=\"simpletable\">\n<caption>OLS Regression Results</caption>\n<tr>\n  <th>Dep. Variable:</th>        <td>ave_hh_sz</td>    <th>  R-squared:         </th> <td>   0.000</td> \n</tr>\n<tr>\n  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>  -0.000</td> \n</tr>\n<tr>\n  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>  0.6794</td> \n</tr>\n<tr>\n  <th>Date:</th>             <td>Tue, 22 Apr 2025</td> <th>  Prob (F-statistic):</th>  <td> 0.410</td>  \n</tr>\n<tr>\n  <th>Time:</th>                 <td>17:55:34</td>     <th>  Log-Likelihood:    </th> <td> -21524.</td> \n</tr>\n<tr>\n  <th>No. Observations:</th>      <td> 48221</td>      <th>  AIC:               </th> <td>4.305e+04</td>\n</tr>\n<tr>\n  <th>Df Residuals:</th>          <td> 48219</td>      <th>  BIC:               </th> <td>4.307e+04</td>\n</tr>\n<tr>\n  <th>Df Model:</th>              <td>     1</td>      <th>                     </th>     <td> </td>    \n</tr>\n<tr>\n  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>    \n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n      <td></td>         <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P>|t|</th>  <th>[0.025</th>    <th>0.975]</th>  \n</tr>\n<tr>\n  <th>Intercept</th> <td>    2.4270</td> <td>    0.003</td> <td>  812.995</td> <td> 0.000</td> <td>    2.421</td> <td>    2.433</td>\n</tr>\n<tr>\n  <th>treatment</th> <td>    0.0030</td> <td>    0.004</td> <td>    0.824</td> <td> 0.410</td> <td>   -0.004</td> <td>    0.010</td>\n</tr>\n</table>\n<table class=\"simpletable\">\n<tr>\n  <th>Omnibus:</th>       <td>1488.463</td> <th>  Durbin-Watson:     </th> <td>   2.003</td>\n</tr>\n<tr>\n  <th>Prob(Omnibus):</th>  <td> 0.000</td>  <th>  Jarque-Bera (JB):  </th> <td>4066.993</td>\n</tr>\n<tr>\n  <th>Skew:</th>           <td> 0.007</td>  <th>  Prob(JB):          </th> <td>    0.00</td>\n</tr>\n<tr>\n  <th>Kurtosis:</th>       <td> 4.423</td>  <th>  Cond. No.          </th> <td>    3.23</td>\n</tr>\n</table><br/><br/>Notes:<br/>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n#### `mrm2` (Months Since Last Donation)\n\n- **Manual t-test**:\n  - t-statistic: **0.1195**, degrees of freedom ≈ 33,394, p = **0.905**\n  - Not statistically significant\n\n- **Regression (`mrm2 ~ treatment`)**:\n  - Coefficient on `treatment`: **0.0137**\n  - p-value: **0.905**\n\nInterpretation: There is no statistically significant difference in prior giving recency between the groups, indicating balance.\n\n---\n\n#### `pwhite` (Proportion White)\n\n- **Manual t-test**:\n  - t-statistic: **–0.5590**, degrees of freedom ≈ 31,876, p = **0.5753**\n  - Not statistically significant\n\n- **Regression (`pwhite ~ treatment`)**:\n  - Coefficient on `treatment`: **–0.0009**\n  - p-value: **0.5753**\n\nInterpretation: Racial composition across treatment and control groups is nearly identical, with no meaningful difference detected.\n\n---\n\n#### `ave_hh_sz` (Average Household Size)\n\n- **Manual t-test**:\n  - t-statistic: **0.8234**, degrees of freedom ≈ 31,960, p = **0.4108**\n  - Not statistically significant\n\n- **Regression (`ave_hh_sz ~ treatment`)**:\n  - Coefficient on `treatment`: **0.0030**\n  - p-value: **0.4108**\n\nInterpretation: Household size is well balanced between the groups, with the regression confirming no significant difference.\n\n### Comments\n\nThe results from all three variables show no statistically significant differences between the treatment and control groups. This supports the integrity of the randomization process and aligns with Table 1 in Karlan and List (2007), which was included in the original paper for the same purpose.\n\nBy demonstrating that key baseline characteristics are similar across groups, we can be more confident that any observed differences in outcome variables can be attributed to the treatment itself rather than to underlying differences in the populations.\n\nThe balance tests confirm that random assignment was successfully implemented in the experiment.\n\n\n\n## Experimental Results\n\n### Charitable Contribution Made\n\nFirst, I analyze whether matched donations lead to an increased response rate of making a donation. \n\n_todo: make a barplot with two bars. Each bar is the proportion of people who donated. One bar for treatment and one bar for control._\n\n::: {#7c2ca50c .cell execution_count=3}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\ndf_k['gave'] = (df_k['amount'] > 0).astype(int)\n\nresponse_rates = df_k.groupby('treatment')['gave'].mean()\nlabels = ['Control', 'Treatment']\n\nplt.figure(figsize=(6, 4))\nplt.bar(labels, response_rates, color=['gray', 'blue'])\nplt.ylabel('Proportion Donated')\nplt.title('Response Rate by Group')\nplt.ylim(0, 0.05)  # adjust as needed\nplt.grid(axis='y', linestyle='--', alpha=0.7)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-4-output-1.png){width=565 height=373}\n:::\n:::\n\n\n_todo: run a t-test between the treatment and control groups on the binary outcome of whether any charitable donation was made. Also run a bivariate linear regression that demonstrates the same finding. (It may help to confirm your calculations match Table 2a Panel A.) Report your statistical results and interpret them in the context of the experiment (e.g., if you found a difference with a small p-value or that was statistically significant at some threshold, what have you learned about human behavior? Use mostly English words, not numbers or stats, to explain your finding.)_\n\n::: {#91589c2c .cell execution_count=4}\n``` {.python .cell-code}\nimport numpy as np\nimport statsmodels.api as sm\nimport statsmodels.formula.api as smf\nfrom scipy import stats\n\n# Ensure 'gave' column is defined (1 if donated, 0 if not)\ndf_k['gave'] = (df_k['amount'] > 0).astype(int)\n\n# Split by group\ngave_treat = df_k[df_k['treatment'] == 1]['gave']\ngave_control = df_k[df_k['treatment'] == 0]['gave']\n\n# --- Manual t-test (Welch's t-test) ---\nmean_treat = gave_treat.mean()\nmean_control = gave_control.mean()\nvar_treat = gave_treat.var(ddof=1)\nvar_control = gave_control.var(ddof=1)\nn_treat = len(gave_treat)\nn_control = len(gave_control)\n\n# Standard error\nse = np.sqrt(var_treat/n_treat + var_control/n_control)\nt_stat = (mean_treat - mean_control) / se\n\n# Degrees of freedom (Welch’s formula)\ndf_num = (var_treat/n_treat + var_control/n_control)**2\ndf_denom = ((var_treat/n_treat)**2 / (n_treat - 1)) + ((var_control/n_control)**2 / (n_control - 1))\ndf_eff = df_num / df_denom\n\n# p-value\np_val = 2 * (1 - stats.t.cdf(abs(t_stat), df=df_eff))\n\nprint(f\"T-test result: t = {t_stat:.4f}, df ≈ {df_eff:.0f}, p = {p_val:.4f}\")\n\n# --- Linear regression: gave ~ treatment ---\nmodel = smf.ols(\"gave ~ treatment\", data=df_k).fit()\nprint(model.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nT-test result: t = 3.2095, df ≈ 36577, p = 0.0013\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                   gave   R-squared:                       0.000\nModel:                            OLS   Adj. R-squared:                  0.000\nMethod:                 Least Squares   F-statistic:                     9.618\nDate:                Tue, 22 Apr 2025   Prob (F-statistic):            0.00193\nTime:                        17:55:34   Log-Likelihood:                 26630.\nNo. Observations:               50083   AIC:                        -5.326e+04\nDf Residuals:                   50081   BIC:                        -5.324e+04\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nIntercept      0.0179      0.001     16.225      0.000       0.016       0.020\ntreatment      0.0042      0.001      3.101      0.002       0.002       0.007\n==============================================================================\nOmnibus:                    59814.280   Durbin-Watson:                   2.005\nProb(Omnibus):                  0.000   Jarque-Bera (JB):          4317152.727\nSkew:                           6.740   Prob(JB):                         0.00\nKurtosis:                      46.440   Cond. No.                         3.23\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\n### Response Rate Analysis\n\nTo test whether offering a matching donation influenced charitable behavior, I examined the **response rate** — the proportion of individuals who made any donation — across treatment and control groups.\n\n#### Statistical Results\n\nUsing a **t-test**, I found a statistically significant difference in donation rates:\n\n- **t = 3.21**, degrees of freedom ≈ 36,577  \n- **p = 0.0013**\n\nI also ran a **bivariate linear regression**:\n\n- `gave ~ treatment`  \n- Coefficient on `treatment`: **0.0042**,  \n- Standard error: **0.0014**  \n- **p = 0.002**\n\nThis confirms that individuals in the treatment group were significantly more likely to donate than those in the control group.\n\n#### Context and Interpretation\n\nThe estimated treatment effect is about **0.42 percentage points** - small in absolute terms, but statistically meaningful. This suggests that **framing a donation opportunity with a matching offer** leads to an increased likelihood that someone contributes, even if the match amount or ratio isn't overwhelming.\n\nIn other words, **people are more responsive to the idea that their donation will be matched**, likely because it enhances their perceived impact or makes the opportunity feel more urgent or meaningful.\n\n#### Comparison to Table 2A\n\nThese results align closely with the findings reported in **Table 2A, Panel A** of Karlan and List (2007):\n\n- Reported control group response rate: **1.8%**  \n- Reported treatment group response rate: **2.2%**  \n- Difference: **0.004** / **0.4 percentage points**\n\nThis nearly matches the **0.0042** effect size estimated in my regression. This agreement supports the accuracy of my replication and reinforces the study’s conclusion: **matching offers boost donation behavior in a statistically and behaviorally significant way**.\n\n> Small psychological nudges, like a match, can meaningfully shift real world decisions, even when the actual financial difference is minor.\n\n\n_todo: run a probit regression where the outcome variable is whether any charitable donation was made and the explanatory variable is assignment to treatment or control. Confirm that your results replicate Table 3 column 1 in the paper._\n\n\n### Differences between Match Rates\n\nNext, I assess the effectiveness of different sizes of matched donations on the response rate.\n\n_todo: Use a series of t-tests to test whether the size of the match ratio has an effect on whether people donate or not. For example, does the 2:1 match rate lead increase the likelihood that someone donates as compared to the 1:1 match rate? Do your results support the \"figures suggest\" comment the authors make on page 8?_\n\n_todo: Assess the same issue using a regression. Specifically, create the variable `ratio1` then regress `gave` on `ratio1`, `ratio2`, and `ratio3` (or alternatively, regress `gave` on the categorical variable `ratio`). Interpret the coefficients and their statistical precision._\n\n_todo: Calculate the response rate difference between the 1:1 and 2:1 match ratios and the 2:1 and 3:1 ratios.  Do this directly from the data, and do it by computing the differences in the fitted coefficients of the previous regression. what do you conclude regarding the effectiveness of different sizes of matched donations?_\n\n\n### Size of Charitable Contribution\n\nIn this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.\n\n_todo: Calculate a t-test or run a bivariate linear regression of the donation amount on the treatment status. What do we learn from doing this analysis?_\n\n_todo: now limit the data to just people who made a donation and repeat the previous analysis. This regression allows you to analyze how much respondents donate conditional on donating some positive amount. Interpret the regression coefficients -- what did we learn? Does the treatment coefficient have a causal interpretation?_ \n\n_todo: Make two plot: one for the treatment group and one for the control. Each plot should be a histogram of the donation amounts only among people who donated. Add a red vertical bar or some other annotation to indicate the sample average for each plot._\n\n\n## Simulation Experiment\n\nAs a reminder of how the t-statistic \"works,\" in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.\n\nSuppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made. \n\nFurther suppose that the true distribution of respondents who do get a charitable donation match of any size  is Bernoulli with probability p=0.022 that a donation is made.\n\n### Law of Large Numbers\n\n_to do:  Make a plot like those on slide 43 from our first class and explain the plot to the reader. To do this, you will simulate 100,00 draws from the control distribution and 10,000 draws from the treatment distribution. You'll then calculate a vector of 10,000 differences, and then you'll plot the cumulative average of that vector of differences. Comment on whether the cumulative average approaches the true difference in means._\n\n\n### Central Limit Theorem\n\n_to do: Make 4 histograms like those on slide 44 from our first class at sample sizes 50, 200, 500, and 1000 and explain these plots to the reader. To do this for a sample size of e.g. 50, take 50 draws from each of the control and treatment distributions, and calculate the average difference between those draws. Then repeat that process 999 more times so that you have 1000 averages. Plot the histogram of those averages. Comment on whether zero is in the \"middle\" of the distribution or whether it's in the \"tail.\"_\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}