{
  "hash": "a9f4d36319f3eeaa08c8c84dff1c72ae",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Poisson Regression Examples\"\nauthor: \"Alexa Gamble\"\ndate: 05/03/2025\ncallout-appearance: minimal # this hides the blue \"i\" icon on .callout-notes\n---\n\n\n## Blueprinty Case Study HW 2\n\n### Introduction\n\nBlueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty's software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty's software and after using it. Unfortunately, such data is not available. \n\nHowever, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm's number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty's software. The marketing team would like to use this data to make the claim that firms using Blueprinty's software are more successful in getting their patent applications approved.\n\n\n### Data\n\n::: {#64d2d3f7 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport numpy as np\n\nblueprinty = pd.read_csv(\"/home/jovyan/Desktop/Marketing Analytics Website : HW's/blueprinty.csv\")\nairbnb = pd.read_csv(\"/home/jovyan/Desktop/Marketing Analytics Website : HW's/airbnb.csv\")\n\nblueprinty\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>patents</th>\n      <th>region</th>\n      <th>age</th>\n      <th>iscustomer</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>Midwest</td>\n      <td>32.5</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>3</td>\n      <td>Southwest</td>\n      <td>37.5</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>4</td>\n      <td>Northwest</td>\n      <td>27.0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>3</td>\n      <td>Northeast</td>\n      <td>24.5</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>3</td>\n      <td>Southwest</td>\n      <td>37.0</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>1495</th>\n      <td>2</td>\n      <td>Northeast</td>\n      <td>18.5</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1496</th>\n      <td>3</td>\n      <td>Southwest</td>\n      <td>22.5</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1497</th>\n      <td>4</td>\n      <td>Southwest</td>\n      <td>17.0</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1498</th>\n      <td>3</td>\n      <td>South</td>\n      <td>29.0</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1499</th>\n      <td>1</td>\n      <td>South</td>\n      <td>39.0</td>\n      <td>0</td>\n    </tr>\n  </tbody>\n</table>\n<p>1500 rows × 4 columns</p>\n</div>\n```\n:::\n:::\n\n\n### Compare histograms and means of number of patents by customer status\n\nBlueprinty customers are not selected at random. It may be important to account for systematic differences in the age and regional location of customers vs non-customers.\n\n::: {#ab731fac .cell execution_count=2}\n``` {.python .cell-code}\ncustomers = blueprinty[blueprinty['iscustomer'] == 1]\nnon_customers = blueprinty[blueprinty['iscustomer'] == 0]\n\nplt.figure(figsize=(10, 5))\nplt.hist(customers['patents'], bins=20, alpha=0.6, label='Customers', edgecolor='black')\nplt.hist(non_customers['patents'], bins=20, alpha=0.6, label='Non-Customers', edgecolor='black')\nplt.xlabel('Number of Patents')\nplt.ylabel('Frequency')\nplt.title('Histogram of Number of Patents by Customer Status')\nplt.legend()\nplt.grid(True)\nplt.show()\n\nmean_customers = customers['patents'].mean()\nmean_non_customers = non_customers['patents'].mean()\n\nprint(f'Customer Mean Number of Patents: {mean_customers}')\nprint(f'Non-Customer Mean Number of Patents: {mean_non_customers}')\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-3-output-1.png){width=816 height=449}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nCustomer Mean Number of Patents: 4.133056133056133\nNon-Customer Mean Number of Patents: 3.4730127576054954\n```\n:::\n:::\n\n\nThe histogram above compares the distribution of patent counts between firms that use Blueprinty software (`iscustomer = 1`) and those that do not (`iscustomer = 0`). A few key patterns emerge:\n\n- The distribution is **right-skewed** for both groups, with the bulk of firms holding between 0 and 6 patents.\n- **Non-customers** are more concentrated around lower patent counts, particularly at 2-4 patents.\n- **Customers** of Blueprinty show a relatively flatter distribution, with more firms holding moderate to higher numbers of patents.\n\nThe summary statistics support this visual trend:\n\n- Non-customers have **3.47 patents** on average (n = 1,019)\n- Customers have **4.13 patents** on average (n = 481)\n\nAlthough this is a modest difference (approximately 0.66 more patents on average), it is consistent with the idea that Blueprinty customers may be more successful or more prolific in obtaining patents. However, it is also possible that other factor, such as firm age or region, may explain the difference, so further analysis is needed before drawing causal conclusions.\n\n\n### Compare regions and ages by customer status\n\n::: {#1575bcaf .cell execution_count=3}\n``` {.python .cell-code}\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\nsns.set_style(\"whitegrid\")\n\nregion_props = pd.crosstab(blueprinty['region'], blueprinty['iscustomer'], normalize='index').reset_index()\nregion_props.columns = ['Region', 'Non-Customers', 'Customers']\nregion_props = pd.melt(region_props, id_vars='Region', var_name='Customer Type', value_name='Proportion')\n\nplt.figure(figsize=(8, 5))\nsns.barplot(data=region_props, x='Region', y='Proportion', hue='Customer Type')\nplt.title('Proportion of Firms by Region and Customer Status')\nplt.ylabel('Proportion')\nplt.xlabel('Region')\nplt.legend(title='Customer Type')\nplt.xticks(rotation=45)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-4-output-1.png){width=757 height=469}\n:::\n:::\n\n\n::: {#36d3466f .cell execution_count=4}\n``` {.python .cell-code}\nplt.figure(figsize=(6, 5))\nsns.boxplot(data=blueprinty, x='iscustomer', y='age')\nplt.title('Age of Firms by Customer Status')\nplt.xlabel('Customer Status (0 = Non-Customer, 1 = Customer)')\nplt.ylabel('Years Since Incorporation')\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-5-output-1.png){width=565 height=468}\n:::\n:::\n\n\nThe region plot above shows notable variation in customer distribution across regions:\n\n- In most regions (Midwest, Northwest, South, Southwest), the majority of firms are **non-customers**, with Blueprinty customers making up only around 15–20% of firms.\n- The **Northeast** stands out as an exception, where nearly **half of the firms** are Blueprinty customers. This suggests that Blueprinty may have a stronger market presence or better adoption in that region.\n\nThe boxplot comparing firm age by customer status shows:\n\n- The **median age** of customers and non-customers is very similar, both around 25–27 years.\n- The **spread of firm ages** is also comparable, though customers appear to have a slightly higher upper range, with some firms approaching 50 years of age.\n- There’s no strong visual evidence of systematic age differences between customers and non-customers, but customers might skew slightly older on average.\n\nTogether, these plots suggest that while **age** may not be a major confounding factor, **region** could be, especially due to the Northeast's unusual customer concentration. This is important to account for in any causal claims about Blueprinty’s effectiveness.\n\n\n### Estimation of Simple Poisson Model\n\nSince our outcome variable of interest can only be small integer values per a set unit of time, we can use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. We start by estimating a simple Poisson model via Maximum Likelihood.\n\n#### Likelihood Function\n\nFor a Poisson model where $Y_i \\sim \\text{Poisson}(\\lambda)$, the probability mass function is:\n\n$$\nf(Y_i | \\lambda) = \\frac{e^{-\\lambda} \\lambda^{Y_i}}{Y_i!}\n$$\n\nAssuming independence across $n$ observations, the **likelihood** is:\n\n$$\nL(\\lambda) = \\prod_{i=1}^{n} \\frac{e^{-\\lambda} \\lambda^{Y_i}}{Y_i!}\n$$\n\nTaking the natural log of the likelihood (log-likelihood):\n\n$$\n\\ell(\\lambda) = \\sum_{i=1}^{n} \\left( -\\lambda + Y_i \\log(\\lambda) - \\log(Y_i!) \\right)\n$$\n\n::: {#587f934f .cell execution_count=5}\n``` {.python .cell-code}\nfrom scipy.special import gammaln\n\ndef poisson_log_likelihood(lmbda, y):\n    if lmbda <= 0:\n        return -np.inf\n    return np.sum(-lmbda + y * np.log(lmbda) - gammaln(y + 1)) \n```\n:::\n\n\n### Plot of Log-Likelihood Across Lambda Values\n\n::: {#c297ddb4 .cell execution_count=6}\n``` {.python .cell-code}\nimport numpy as np\n\ny = blueprinty['patents'].values\n\nlambda_vals = np.linspace(0.1, 10, 200)\n\nlog_liks = [poisson_log_likelihood(lmbda, y) for lmbda in lambda_vals]\n\nplt.figure(figsize=(8, 5))\nplt.plot(lambda_vals, log_liks)\nplt.title(\"Log-Likelihood of Poisson Model vs Lambda\")\nplt.xlabel(\"Lambda\")\nplt.ylabel(\"Log-Likelihood\")\nplt.grid(True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-7-output-1.png){width=696 height=449}\n:::\n:::\n\n\n### Solving for MLE of Lambda (Analytical Derivation)\n\nTo find the MLE of $\\lambda$, we take the log-likelihood:\n\n$$\n\\ell(\\lambda) = \\sum_{i=1}^n \\left( -\\lambda + Y_i \\log(\\lambda) - \\log(Y_i!) \\right)\n$$\n\nNow take the derivative with respect to $\\lambda$:\n\n$$\n\\frac{d\\ell}{d\\lambda} = \\sum_{i=1}^n \\left( -1 + \\frac{Y_i}{\\lambda} \\right)\n= -n + \\frac{1}{\\lambda} \\sum_{i=1}^n Y_i\n$$\n\nSet the derivative equal to zero and solve:\n\n$$\n-n + \\frac{1}{\\lambda} \\sum_{i=1}^n Y_i = 0\n$$\n\n$$\n\\frac{1}{\\lambda} \\sum_{i=1}^n Y_i = n\n$$\n\n$$\n\\lambda_{\\text{MLE}} = \\frac{1}{n} \\sum_{i=1}^n Y_i = \\bar{Y}\n$$\n\nThus, the maximum likelihood estimate of $\\lambda$ is simply the **sample mean** of $Y$, which makes intuitive sense: the Poisson distribution models counts with mean $\\lambda$, so the best estimate of $\\lambda$ is just the average count in the data.\n\n### Find MLE of Lambda via Optimization\n\n::: {#a62379ac .cell execution_count=7}\n``` {.python .cell-code}\nfrom scipy.optimize import minimize_scalar\nfrom scipy.special import gammaln\n\ndef neg_poisson_log_likelihood(lmbda, y):\n    if lmbda <= 0:\n        return np.inf\n    return -np.sum(-lmbda + y * np.log(lmbda) - gammaln(y + 1))\n\ny = blueprinty['patents'].values\n\nresult = minimize_scalar(neg_poisson_log_likelihood, bounds=(0.1, 10), args=(y,), method='bounded')\n\nlambda_mle = result.x\nlambda_mle\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n3.684666226134359\n```\n:::\n:::\n\n\n### Estimation of Poisson Regression Model\n\nNext, we extend our simple Poisson model to a Poisson Regression Model such that $Y_i = \\text{Poisson}(\\lambda_i)$ where $\\lambda_i = \\exp(X_i'\\beta)$. The interpretation is that the success rate of patent awards is not constant across all firms ($\\lambda$) but rather is a function of firm characteristics $X_i$. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.\n\n_todo: Update your likelihood or log-likelihood function with an additional argument to take in a covariate matrix X. Also change the parameter of the model from lambda to the beta vector. In this model, lambda must be a positive number, so we choose the inverse link function g_inv() to be exp() so that_ $\\lambda_i = e^{X_i'\\beta}$. _For example:_\n\n```\npoisson_regression_likelihood <- function(beta, Y, X){\n   ...\n}\n```\n\n_todo: Use your function along with R's optim() or Python's sp.optimize() to find the MLE vector and the Hessian of the Poisson model with covariates. Specifically, the first column of X should be all 1's to enable a constant term in the model, and the subsequent columns should be age, age squared, binary variables for all but one of the regions, and the binary customer variable. Use the Hessian to find standard errors of the beta parameter estimates and present a table of coefficients and standard errors._\n\n_todo: Check your results using R's glm() function or Python sm.GLM() function._\n\n_todo: Interpret the results._ \n\n_todo: What do you conclude about the effect of Blueprinty's software on patent success? Because the beta coefficients are not directly interpretable, it may help to create two fake datasets: X_0 and X_1 where X_0 is the X data but with iscustomer=0 for every observation and X_1 is the X data but with iscustomer=1 for every observation. Then, use X_0 and your fitted model to get the vector of predicted number of patents (y_pred_0) for every firm in the dataset, and use X_1 to get Y_pred_1 for every firm. Then subtract y_pred_1 minus y_pred_0 and take the average of that vector of differences._\n\n_todo: Check your results using R's glm() function or Python sm.GLM() function._\n\n_todo: Interpret the results._ \n\n_todo: What do you conclude about the effect of Blueprinty's software on patent success? Because the beta coefficients are not directly interpretable, it may help to create two fake datasets: X_0 and X_1 where X_0 is the X data but with iscustomer=0 for every observation and X_1 is the X data but with iscustomer=1 for every observation. Then, use X_0 and your fitted model to get the vector of predicted number of patents (y_pred_0) for every firm in the dataset, and use X_1 to get Y_pred_1 for every firm. Then subtract y_pred_1 minus y_pred_0 and take the average of that vector of differences._\n\n<!-- ```{python}\nimport numpy as np\nimport pandas as pd\nfrom patsy import dmatrix\nfrom scipy.optimize import minimize\nfrom scipy.special import gammaln\nimport math\n\n# Assuming `blueprinty` is a pandas DataFrame already loaded\nblueprinty['age2'] = blueprinty['age'] ** 2\n\n# Create region dummies, dropping the first category to avoid multicollinearity\nregion_dummies = pd.get_dummies(blueprinty['region'], drop_first=True)\n\n# Construct X matrix\nX = pd.concat([\n    pd.Series(1, index=blueprinty.index, name='Intercept'),\n    blueprinty[['age', 'age2']],\n    region_dummies,\n    blueprinty[['iscustomer']]\n], axis=1)\n\n# Response variable\nY = blueprinty['patents'].values\n\nX_mat = X.values.astype(float)  # enforce numeric dtype\n\ninit_beta = np.zeros(X_mat.shape[1], dtype=float)\n\n# Step 2: Define negative log-likelihood function\ndef neg_loglik(beta, Y, X):\n    eta = X @ beta\n    lambda_ = np.exp(eta)\n    return -np.sum(Y * np.log(lambda_) - lambda_ - gammaln(Y + 1))\n\n\n# Step 3: Optimize\nX_mat = X.values\ninit_beta = np.zeros(X_mat.shape[1])\nres = minimize(\n    neg_loglik,\n    init_beta,\n    args=(Y, X_mat),\n    method='BFGS',\n    options={'disp': False}\n)\n\n# Step 4: Coefficients and standard errors\nbeta_hat = res.x\nhessian_inv = res.hess_inv\nse_beta = np.sqrt(np.diag(hessian_inv))\n\n# Step 5: Coefficient table\ncoef_table = pd.DataFrame({\n    'Term': X.columns,\n    'Coefficient': beta_hat,\n    'Std_Error': se_beta\n})\n\n# Display table (formatted output)\nprint(coef_table.round(3).to_string(index=False))\n\n``` -->\n\n\n\n## AirBnB Case Study\n\n### Introduction\n\nAirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City.  The data include the following variables:\n\n:::: {.callout-note collapse=\"true\"}\n### Variable Definitions\n\n    - `id` = unique ID number for each unit\n    - `last_scraped` = date when information scraped\n    - `host_since` = date when host first listed the unit on Airbnb\n    - `days` = `last_scraped` - `host_since` = number of days the unit has been listed\n    - `room_type` = Entire home/apt., Private room, or Shared room\n    - `bathrooms` = number of bathrooms\n    - `bedrooms` = number of bedrooms\n    - `price` = price per night (dollars)\n    - `number_of_reviews` = number of reviews for the unit on Airbnb\n    - `review_scores_cleanliness` = a cleanliness score from reviews (1-10)\n    - `review_scores_location` = a \"quality of location\" score from reviews (1-10)\n    - `review_scores_value` = a \"quality of value\" score from reviews (1-10)\n    - `instant_bookable` = \"t\" if instantly bookable, \"f\" if not\n\n::::\n\n\n_todo: Assume the number of reviews is a good proxy for the number of bookings. Perform some exploratory data analysis to get a feel for the data, handle or drop observations with missing values on relevant variables, build one or more models (e.g., a poisson regression model for the number of bookings as proxied by the number of reviews), and interpret model coefficients to describe variation in the number of reviews as a function of the variables provided._\n\n#### Data Cleaning and Preparation\n\n::: {#fd22f9fe .cell execution_count=8}\n``` {.python .cell-code}\ncolumns_needed = [\n    \"number_of_reviews\", \"days\", \"room_type\", \"bathrooms\", \"bedrooms\", \"price\",\n    \"review_scores_cleanliness\", \"review_scores_location\", \"review_scores_value\",\n    \"instant_bookable\"\n]\nairbnb = airbnb[columns_needed].dropna()\n\n# Convert 'instant_bookable' to binary\nairbnb[\"instant_bookable\"] = (airbnb[\"instant_bookable\"] == \"t\").astype(int)\n\n# One-hot encode 'room_type' (drop first category)\nairbnb = pd.get_dummies(airbnb, columns=[\"room_type\"], drop_first=True)\n```\n:::\n\n\n#### Explatory Data Analysis \n\n::: {#7682fe3c .cell execution_count=9}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Histogram of reviews\nsns.histplot(airbnb[\"number_of_reviews\"], bins=50)\nplt.title(\"Distribution of Number of Reviews\")\nplt.xlabel(\"Number of Reviews\")\nplt.ylabel(\"Count\")\nplt.show()\n\n# Reviews by room type\nsns.boxplot(x=\"room_type_Private room\", y=\"number_of_reviews\", data=airbnb)\nplt.title(\"Reviews by Room Type (Private Room Indicator)\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-10-output-1.png){width=610 height=449}\n:::\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-10-output-2.png){width=593 height=449}\n:::\n:::\n\n\n#### Poisson Regression Model\n\n::: {#12ce7cfe .cell execution_count=10}\n``` {.python .cell-code}\nfrom scipy.optimize import minimize\nfrom scipy.special import gammaln\n\n# Define Poisson log-likelihood function\ndef poisson_log_likelihood(beta, Y, X):\n    lambda_i = np.exp(X @ beta)\n    return -np.sum(Y * np.log(lambda_i) - lambda_i - gammaln(Y + 1))\n\n# Define response and predictors\nY = airbnb[\"number_of_reviews\"].to_numpy()\npredictor_cols = [\n    \"days\", \"bathrooms\", \"bedrooms\", \"price\", \"review_scores_cleanliness\",\n    \"review_scores_location\", \"review_scores_value\", \"instant_bookable\"\n] + [col for col in airbnb.columns if col.startswith(\"room_type_\")]\n\nX = airbnb[predictor_cols]\nX.insert(0, \"intercept\", 1.0)\nX = X.to_numpy(dtype=float)\n\n# Estimate MLE via optimization\ninitial_beta = np.zeros(X.shape[1])\nresult = minimize(poisson_log_likelihood, initial_beta, args=(Y, X), method='BFGS')\n\nbeta_hat = result.x\nstandard_errors = np.sqrt(np.diag(result.hess_inv))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/tmp/ipykernel_90863/569273671.py:6: RuntimeWarning:\n\noverflow encountered in exp\n\n/tmp/ipykernel_90863/569273671.py:7: RuntimeWarning:\n\ninvalid value encountered in subtract\n\n/tmp/ipykernel_90863/569273671.py:6: RuntimeWarning:\n\noverflow encountered in exp\n\n/tmp/ipykernel_90863/569273671.py:7: RuntimeWarning:\n\ninvalid value encountered in subtract\n\n/tmp/ipykernel_90863/569273671.py:6: RuntimeWarning:\n\noverflow encountered in exp\n\n/tmp/ipykernel_90863/569273671.py:7: RuntimeWarning:\n\ninvalid value encountered in subtract\n\n```\n:::\n:::\n\n\n#### Coefficient Table (WRONG!!!!!)\n\n::: {#4caf6b74 .cell execution_count=11}\n``` {.python .cell-code}\ncoef_table = pd.DataFrame({\n    \"Coefficient\": beta_hat,\n    \"Std. Error\": standard_errors\n}, index=[\"Intercept\"] + predictor_cols)\n\ncoef_table\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Coefficient</th>\n      <th>Std. Error</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Intercept</th>\n      <td>0.752383</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>days</th>\n      <td>1028.812325</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>bathrooms</th>\n      <td>0.837809</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>bedrooms</th>\n      <td>0.888581</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>price</th>\n      <td>105.112261</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>review_scores_cleanliness</th>\n      <td>6.961841</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>review_scores_location</th>\n      <td>7.034069</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>review_scores_value</th>\n      <td>6.987912</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>instant_bookable</th>\n      <td>0.194070</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>room_type_Private room</th>\n      <td>0.344474</td>\n      <td>1.0</td>\n    </tr>\n    <tr>\n      <th>room_type_Shared room</th>\n      <td>0.016666</td>\n      <td>1.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}